[package]
name = "gencheck-key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
hex-literal = "0.4.1"
rand = "0.8.5"
sha2 = "0.10.7"
